
// import img from './components/assets/haworthiaRetusa.jpg'
// import img2 from './components/assets/cordonSanJose.jpg'
// import img3 from './components/assets/desconocida4.jpg'

const prod = [
    { 
        id:1,
        name:"Cordón de San josé",
        // image: {img},
        imgUrl: "https://via.placeholder.com/600/f66b97",
        price: "$350",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:2,
        name:"Haworthia Retusa",
        // image: {img2} ,
        imgUrl: "https://via.placeholder.com/600/f66b97",
        price: "$300",
        // irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol moderado/poco.",
    },
    { 
        id:3,
        name:"Cubre Maceta",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$250",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:4,
        name:"Rosario",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$200 - $250",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:5,
        name:"Planta Fantasma",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$250 - $300",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:6,
        name:"Planta cebra",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$300",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:7,
        name:"Aeonium Kiwi",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$200 - $400",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:8,
        name:"Echeveria runyonii",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$250 - $350",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:9,
        name:"Aeonium Haworthii",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$250 - $350",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:10,
        name:"Graptosedum Francesco Baldi",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$200 - $300",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:11,
        name:"Cubremacetas1",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$250",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:12,
        name:"Cubremacetas2",
        // image: {img3} ,
        imgUrl:"https://via.placeholder.com/600/810b14",
        price: "$300",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    
]

export default prod;