
// import img from './components/assets/haworthiaRetusa.jpg'
// import img2 from './components/assets/cordonSanJose.jpg'
// import img3 from './components/assets/desconocida4.jpg'

const prod = [
    { 
        id: "1",
        name:"Cordón de San josé",
        // image: {img},
        imgUrl: "https://dl.dropbox.com/s/4y915udz688x1j6/cordonSanJose.jpg",
        price: "$350",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:"2",
        name:"Haworthia Retusa",
        // image: {img2} ,
        imgUrl: "https://dl.dropbox.com/s/qfyv8cyxq7t5bff/haworthiaRetusa.jpg",
        price: "$300",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol moderado/poco.",
    },
    { 
        id:3,
        name:"Cubre Maceta",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/7ptnxa8csgrkjfh/desconocida4.jpg",
        price: "$250",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:"4",
        name:"Rosario",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/t0if2o6i5e2b0ea/rosario.jpg",
        price: "$200 - $250",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:5,
        name:"Planta Fantasma",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/qwlg7g8ovjhp2ao/PlantaFantasma.jpg",
        price: "$250 - $300",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol moderado/poco.",
    },
    { 
        id:6,
        name:"Planta cebra",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/p23qvp2hnlajpn9/plantaCebra.jpg",
        price: "$300",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio/poco (mucho sol hara que se sequen las puntas de la planta).",
    },
    { 
        id:7,
        name:"Aeonium Kiwi",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/g60qsbhbsjb73fb/aeoniumKiwi.jpg",
        price: "$200 - $400",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio (preferentemente sol de la mañana o tarde/noche).",
    },
    { 
        id:8,
        name:"Echeveria runyonii",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/jhv4fo5pcezmnlg/echeveriaRunyonii.jpg",
        price: "$250 - $350",
        irrigationFrequency: "1/2 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:9,
        name:"Aeonium Haworthii",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/edn4jykycyxt43j/aeoniumHaworthii2.jpg",
        price: "$350 - $500",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:10,
        name:"Graptosedum Francesco Baldi",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/pb8z5skxl3rymtr/graptosedumFrancesco.jpg",
        price: "$200 - $300",
        irrigationFrequency: "2/3 veces por semana.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:11,
        name:"Cactus",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/rzlatsjet9ncdrs/cactus1.jpg",
        price: "$300",
        irrigationFrequency: "1 vez por semana, 2 como mucho.",
        ubication: "Planta de exterior, sol intemertmedio.",
    },
    { 
        id:12,
        name:"Cactus",
        // image: {img3} ,
        imgUrl:"https://dl.dropbox.com/s/84n6io50wnri4gp/cactus2.jpg",
        price: "$300",
        irrigationFrequency: "1 vez por semana, 2 como mucho.",
        ubication: "Planta de exterior, resiste sol las 24hs.",
    },
    
]

export default prod;